# Generated by Django 4.0.5 on 2022-06-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
