# Generated by Django 4.0.5 on 2022-07-22 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_orders_amou_orders_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='total',
            new_name='amount',
        ),
    ]
