# Generated by Django 4.0.5 on 2022-07-22 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rename_total_orders_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
    ]
