# Generated by Django 4.0.5 on 2022-08-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_orders_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='amount',
            new_name='amt',
        ),
    ]
