# Generated by Django 4.0.5 on 2022-08-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_rename_amount_orders_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amt',
        ),
    ]
